/**
 * ui/theme.js — VISUAL-ONLY TOKENS
 * 
 * VISUAL AI: EDIT HERE FREELY (colours, radii, shadows, animation).
 * TEXT AI: DO NOT EDIT THIS FILE FOR TEXT — TEXT LIVES IN ../content/copy.js
 * 
 * This file is the sanctioned place for colours/shapes/icons. Changing
 * values here must NOT alter any user-facing string.
 * 
 * Tailwind config reads these tokens conceptually; keep in sync with
 * tailwind.config.js and client/src/index.css
 */

export const theme = {
  colors: {
    // Shell
    bg: "#0a1e2e",
    bgSoft: "#0f2231",
    bgMuted: "#142a3d",
    border: "rgba(255,255,255,0.10)",
    borderHover: "rgba(255,255,255,0.18)",
    // Accent
    cream: "#f3ecd8",
    amber: "#fbbf24",
    amberSoft: "#fde68a",
    emerald: "#10b981",
    rose: "#f43f5e",
    sky: "#7ec8e6",
    // Café (if you reintroduce split theme, use these)
    cafeBg: "#121416",
    cafeCard: "#1e2326",
    terracotta: "#c9734b",
    sage: "#8aa899",
  },
  radius: {
    card: "24px",
    cardSm: "16px",
    pill: "9999px",
    input: "12px",
  },
  shadow: {
    card: "0 12px 40px rgba(0,0,0,0.45)",
    soft: "0 8px 24px rgba(0,0,0,0.28)",
  },
  // Tailwind class maps — visual AI can tune these strings; never put raw text here
  classes: {
    pageBg: "bg-[#0a1e2e]",
    card: "rounded-[24px] bg-[#0f2231] border border-white/10 shadow-xl",
    cardHover: "hover:border-white/15 hover:shadow-2xl hover:-translate-y-0.5 transition-all duration-300",
    buttonPrimary: "rounded-full bg-[#f3ecd8] hover:bg-white text-[#0e2533] font-extrabold shadow-md transition-all duration-200 hover:scale-[1.02] active:scale-[0.98]",
    buttonGhost: "rounded-full bg-white/10 hover:bg-white/15 border border-white/10 text-white font-bold transition-colors",
    input: "rounded-xl bg-white/10 border border-white/15 text-white placeholder:text-white/30 focus:border-amber-400/50 focus:bg-white/[0.12] transition-colors",
  },
  // Icon registry — add SVG or emoji here; components import icons, not hardcode text
  icons: {
    // Use inline SVG strings or emoji; adding an icon here does not change copy
    dice: "🎲",
    crown: "👑",
    robot: "🤖",
    eye: "👁",
    link: "🔗",
    users: "👥",
    mask: "🕵️",
    book: "📖",
    gamepad: "🎮",
    star: "⭐",
    lightbulb: "💡",
  },
};
