/**
 * content/copy.js — SINGLE SOURCE OF TRUTH FOR ALL USER-FACING TEXT
 * 
 * TEXT LOCK — DO NOT EDIT THIS FILE ON NORMAL PROMPTS
 * --------------------------------------------------------------
 * - All strings the player reads must live here.
 * - Visual AI (theme/icons/colours/shapes) MUST NOT change any value here
 *   — even when user says "revamp UI / redesign / make it pretty" normally.
 * - Text changes require explicit user prompt: "change text: ..."
 * - If you need a new label, ask the user or add a new key here only with user approval.
 * 
 * Visual AI: you may import from here but never modify. Only touch:
 *   client/src/ui/theme.js, client/src/ui/primitives.jsx, client/src/index.css,
 *   tailwind.config.js, client/public/assets/*
 */

export const copy = {
  // Top bar / App shell
  app: {
    brand: "LUCKY STREET",
    sub: "PARTY LOBBY",
    live: "Live",
    connecting: "Connecting…",
    edit: "Edit",
    setProfile: "Set Profile",
  },

  // Main page / RoomBrowser
  roomBrowser: {
    title: "Game Rooms",
    subtitle: "Jump in or start your own.",
    newGame: "+ New Game",
    searchPlaceholder: "Search rooms…",
    roomsSuffix: "rooms",
    emptyTitle: "No games right now",
    emptyDesc: "Start a new one - it’ll show up instantly.",
    quickTipsTitle: "Quick tips",
    quickTips: [
      "Your name stays saved for next time.",
      "Pick a unique name - try another if taken.",
      "Share your invite link to play together.",
    ],
  },

  // RoomCard
  roomCard: {
    open: "Open",
    inProgress: "In Progress",
    ended: "Ended",
    slotsLabel: "SLOTS",
    join: "Join",
    spectate: "Spectate",
    watching: "watching",
    hostPrefix: "Host:",
  },

  // Join by ID box
  joinById: {
    title: "Join by Room ID",
    desc: "Enter the 4-character code from your friend’s invite link.",
    placeholder: "A1B2",
    join: "Join",
    errInvalid: "Enter 4-character ID (A-Z, 0-9)",
  },

  // Create Room modal
  createRoom: {
    title: "Create Room",
    subtitle: "Pick a game to start",
    create: "Create Room",
    creating: "Creating…",
    footer: "You’ll get a code to share • options in lobby",
    errors: {
      chooseGame: "Choose a game",
      notConnected: "Not connected - please wait a moment and try again",
      slow: "Connection slow - please try again",
    },
  },

  // Identity / onboarding
  identity: {
    welcomeTitle: "Welcome to Lucky Street",
    pickingTitle: "Welcome to Lucky Street",
    subtitle: "Choose how you’ll appear to others.",
    blockingNote: "Choose a name to join",
    yourName: "YOUR NAME",
    placeholder: "e.g., Alex",
    hint: "Others will see this.",
    changeAnytime: "You can change your name and avatar anytime.",
    cancel: "Cancel",
    save: "Save & Continue",
    enterLobby: "Enter Lobby",
    checking: "Checking…",
    errors: {
      whatCall: "What should we call you?",
      tooShort: "Name is too short",
      tooLong: "That name is a bit long",
      invalid: "Use letters, numbers and - _ ' .",
      taken: "That name is taken - try another",
      notConnected: "Not connected - please wait a moment and try again",
      slow: "Connection is slow - please try again",
    },
  },

  // Lobby — generic
  lobby: {
    leave: "Leave",
    roomPrefix: "Room",
    hostPrefix: "Host:",
    board: "Board",
    myControls: "My Controls",
    youWereRemoved: "You were removed",
    youNoLonger: "You’re no longer in this game.",
    backToGames: "Back to games",
    tryingAgain: "Trying again - tap Retry if needed.",
    doubleCheck: "Double-check the code and try again.",
    tryAgain: "Try again",
    joining: "Joining",
    kicked: "You’re no longer in this game.",
    // Board / code share
    joinCode: "JOIN CODE",
    share: "Share:",
    everyoneLook: "Everyone look here!",
    copyLink: "Copy link",
    linkCopied: "Link copied!",
    // Who's here
    whosHere: "Who’s here",
    changeFromMain: "Change your name and picture from the main screen.",
    you: "YOU",
    watching: "Watching",
    watch: "Watch",
    joinToPlay: "Join to play",
    youreWatching: "You’re watching - tap Join to play",
    watchOrJoin: "Watch or join the game",
    onlyOne: "You’re the only one here",
    switchedToSpectator: "Switched to spectator",
    spectating: "Spectating",
    joinedAsPlayer: "Joined as player",
    // Veil Street lobby card
    veilStreet: "Veil Street",
    needToStart: "need to start",
    ready: "Ready",
    needMore: "Need more",
    readyToStart: "Ready to start!",
    needMoreToStart: "Need more to start",
    startQuest: "Start Quest",
    addBotsOrWait: "Add bots or wait for players to reach",
    // Add Bots
    addBots: "Add Bots",
    botsNotSupported: "Bots not supported for",
    switchToVeil: "Switch to Veil Street to use bots, or play with humans only.",
    roomFull: "Room full",
    removeToAdd: "remove a player/bot to add more.",
    leaveEmpty: "Leave empty for random name",
    add: "Add",
    botsTakeSpot: "bots take a spot and look the same.",
    addedBot: "Added bot",
    removedBot: "Removed",
    // Game selector
    game: "Game",
    noBots: " (no bots)",
    bots: " (bots)",
    lobbyLocked: "Lobby locked during game",
    evilExtras: "evil extras for",
    merlinAssassin: "Merlin+Assassin always",
    resetToChange: "Reset game to change settings.",
    onlyHost: "Only the host can change these settings.",
    max: "MAX",
    // Quest track (in-game)
    quest: "QUEST",
    rejected: "REJECTED",
    rejectsEvil: "5 rejects = Evil wins • Good 3 → Assassin guesses Merlin",
    q4needs: "Q4 needs 2 fails (7+ players)",
    needs2: "needs 2",
    twoFails: "2 fails",
    // Modals
    whatToDoWith: "What to do with",
    makeHost: "Make host",
    remove: "Remove",
    close: "Close",
    isNowHost: "is now host",
    kickedToast: "Kicked",
    // Rules
    howToPlay: "How to Play",
    howToWin: "How to win:",
    howToWinDesc: "Good wins by completing 3 quests. Evil wins by failing 3 quests, blocking teams 5 times, or having the Assassin find Merlin at the end.",
    goodTeam: "GOOD TEAM",
    goodDesc: "• Loyal - no power<br/>• Merlin - knows Evil (except Mordred hides)<br/>• Percival - knows Merlin (but Morgana pretends)",
    evilTeam: "EVIL TEAM",
    evilDesc: "• Minion - with Evil<br/>• Assassin - hunts Merlin<br/>• Morgana - pretends to be Merlin<br/>• Mordred - hidden from Merlin<br/>• Oberon - works alone",
    howRound: "How a round works",
    howRoundDesc: "1. Leader picks a team → 2. Everyone votes → 3. If most say yes, that team secretly picks Success or Fail. Good must pick Success. One Fail usually fails the quest - the 4th quest needs 2 fails when you have 7+ players.",
    extraEvil: "extra Evil",
    players: "Players:",
    botsSupported: "(bots supported)",
    noBotsLong: "(no bots)",
    defaultMax: "Default max",
    options: "Options",
    hostCanStart: "Host can start when",
    playersReady: "players ready. Rules are specific to this game.",
  },

  // Common toasts / misc
  common: {
    needPlayers: "Need players - have",
    addBots: "Add bots.",
    startFailed: "Start failed",
    questStarted: "Quest started - roles dealt",
    resetFailed: "Reset failed",
    gameReset: "Game reset - back to lobby",
    gameSetTo: "Game set to",
    botsRemoved: "Bots removed - this game doesn't support bots",
    thisGameNoBots: "This game doesn't support bots",
    cannotAddDuringGame: "Cannot add bots while game in progress",
    roomFull: "Room full",
    cannotSpectateOnlyPlayer: "Cannot spectate as only player - room would close",
  },
};
